#!/bin/bash

term="st -e"
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
cache="$cachedir/dmenu_recent"

touch "$cache"

most_used=$(sort "$cache" | grep -v "^$" | sort | uniq -c | awk '{print $2}')
run=$((echo "$most_used"; dmenu_path | grep -vxF "$most_used") | dmenu -i "$@")

(echo "$run"; head -n 99 "$cache") > "$cache.$$"

mv "$cache.$$" "$cache"

case "$run" in
    *\;) exec $(echo $term "$run" | sed -e 's/;$//') ;;
    *)   exec "$run" ;;
esac
